### PR TITLE
Producer/Consumer transaction support

### PR DESCRIPTION
**Pull request by fab60**
# Description

Introduce support for consumer/producer transaction. Offset management has been extended in order to provide producer controlled offset committing inside a transaction. API surface area is exposed by the ConsumerProducerTransactionScope.

Fixes # [(Producer transaction support)](https://github.com/Farfetch/kafka-flow/issues/144)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have added tests to cover my changes
-   [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

**Comment by fab60** [comment]
Forgot to say that the feature is based on the v2 branch.

**Comment by filipeesch** [comment]
Hi @fab60, we appreciate your help.

This change is deeper than we thought. In these cases, we think it is better to discuss with us how to implement the feature before implementing it. You can use our [Slack](https://join.slack.com/t/kafkaflow/shared_invite/zt-fqw06n2u-1lA5Mz_VnSPGhRgfT97SPQ) account to do it.

**Review by filipeesch — CHANGES_REQUESTED** [review]
Let's discuss this before merging this PR.
Our vision to support transaction in KafkaFlow is to try to abstract the complexity when working with Confluent Client directly.

**Comment by fab60** [comment]
Hi @filipeesch,

I agree with you that the feature is quite substantial and that this PR is to be considered as a first implementation proposal. It could be nice if we can discuss it as soon as possible. BTW, the slack account invitation seems to be no more valid

**Comment by filipeesch** [comment]
You can use this link: https://join.slack.com/t/kafkaflow/shared_invite/zt-puihrtcl-NnnylPZloAiVlQfsw~RD6Q

**Pull request closed without merging**
